#!/bin/sh
'''exec' "/Users/macintoshssd/Ansible-s3-website project/devops_env/bin/python3.13" "$0" "$@"
' '''
import sys
from ansible.cli.pull import main
if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(main())
